FROM node:18.17.0
# RUN npm install -g nodemon
COPY . .
COPY . . 
COPY .env .env
RUN npm install
EXPOSE 4000
CMD ["node", "index.js"]
# CMD ["npm", "run", "dev"]

# FROM node:18.17.0
# WORKDIR /app
# COPY . . 
# COPY .env .env
# RUN npm install
# EXPOSE 4000
# CMD ["node", "index.js"]
